[GPF-296] Feedback Bar
Venture-Capitol/venture-capitol pull request #149
Opened 2022-04-13 19:28 UTC by konstantin-spiess

Closes: GPF-296

## Comments

TODO: Tests in Firefox, Safari

## Changes

- added routes in backend for: like, dislike, message
- added feedback thumbs, message in frontend in desktop view
- added slack secret to prod backend deploy

2022-04-14 08:30 UTC, SkyGuardian42 commented
Oh nice, schaue ich mir heute Nachmittag an, richtig nice!

2022-04-15 17:02 UTC, SkyGuardian42 commented
Hey, gerade beim Testen ist mir aufgefallen dass das Popup teilweise komisch positioniert wird, wenn der Viewport größer ist: 

![image](https://user-images.githubusercontent.com/12611076/163598026-0505f10b-3696-4924-9692-a55f6acfcd90.png)

![image](https://user-images.githubusercontent.com/12611076/163598080-123b48a1-0d15-4f20-a1d8-5e810362e20b.png)

---

Nicer z-index :laughing: 
![image](https://user-images.githubusercontent.com/12611076/163598190-17d0ef67-ddfa-4585-a34b-a28570df5e44.png)


---

Super nice dass du sogar einen failure-state eingebaut hast! :ok_hand:
![image](https://user-images.githubusercontent.com/12611076/163598395-52aaa5e3-cead-4b4c-ab4d-93634e829070.png)
 
---
Super fancy dass auch noch Animationen dabei sind, der wiggelnde Error-Button und die like / dislike Buttons :heart_eyes: 
![gif](https://user-images.githubusercontent.com/12611076/163598713-2dba0ef0-4737-4ef2-ac58-4fdb25a0328d.gif)

2022-04-15 17:05 UTC, SkyGuardian42 commented on apps/frontend/src/components/Feedback/Feedback.tsx
> +		e: React.MouseEvent,
e wird nicht verwendet, können wir das rausnehmen?

2022-04-15 18:39 UTC, konstantin-spiess commented on apps/frontend/src/components/Feedback/Feedback.tsx
> +		e: React.MouseEvent,
> Hey, gerade beim Testen ist mir aufgefallen dass das Popup teilweise komisch positioniert wird, wenn der Viewport größer ist:
> 
> ![image](https://user-images.githubusercontent.com/12611076/163598026-0505f10b-3696-4924-9692-a55f6acfcd90.png)
> 
> ![image](https://user-images.githubusercontent.com/12611076/163598080-123b48a1-0d15-4f20-a1d8-5e810362e20b.png)
> 
> Nicer z-index 😆 ![image](https://user-images.githubusercontent.com/12611076/163598190-17d0ef67-ddfa-4585-a34b-a28570df5e44.png)
> 
> Super nice dass du sogar einen failure-state eingebaut hast! 👌 ![image](https://user-images.githubusercontent.com/12611076/163598395-52aaa5e3-cead-4b4c-ab4d-93634e829070.png)
> 
> Super fancy dass auch noch Animationen dabei sind, der wiggelnde Error-Button und die like / dislike Buttons 😍 ![gif](https://user-images.githubusercontent.com/12611076/163598713-2dba0ef0-4737-4ef2-ac58-4fdb25a0328d.gif)

Huch, das ist mir entgangen. Hab die Position nochmal angepasst.

2022-04-15 18:39 UTC, konstantin-spiess commented on apps/frontend/src/components/Feedback/Feedback.tsx
> +		e: React.MouseEvent,
> e wird nicht verwendet, können wir das rausnehmen?

Ist gemacht

2022-04-15 19:43 UTC, SkyGuardian42 commented on apps/frontend/src/components/Feedback/Feedback.tsx
> +		e: React.MouseEvent,
Krass, sieht gut aus bei mir! Habs gerade auch noch auf Safari getestet, sieht auch super aus :ok_hand:

2022-04-15 19:43 UTC, SkyGuardian42 approved these changes

2022-04-15 19:44 UTC, SkyGuardian42 requested changes
Wir müssen noch die environment variable in den neuen deployprozess reinschreiben, die datei heißt deploy.yaml

2022-04-15 19:45 UTC, SkyGuardian42 commented
Die Schritte sind fast gleich, müsste bloß in der Datei übernommen werden

2022-04-21 01:17 UTC, SkyGuardian42 submitted a review, later dismissed

2022-05-04 19:22 UTC, SkyGuardian42 approved these changes

2022-05-04 19:22 UTC, merged