[GPF-199] Entscheidungsseite Gesellschaftsformen
Venture-Capitol/venture-capitol pull request #92
Opened 2022-01-29 18:58 UTC by luis-rieke

Closes: [GPF-199](https://spacifik.atlassian.net/browse/GPF-199)

## Changes

- Verlinkung Button Landing Page auf eigene Seite für die Entscheidung welche Gesellschaftsform
- Content der Entscheidungsseite Gesellschaftsform

2022-02-01 12:31 UTC, SkyGuardian42 requested changes

2022-02-01 12:31 UTC, SkyGuardian42 commented on apps/frontend/src/pages/Index/Index.tsx
> +	);
Warum wird hier useCallback verwendet?

2022-02-01 12:31 UTC, SkyGuardian42 commented on apps/frontend/src/pages/Index/Index.tsx
> +					<Button variant='secondary' onClick={handleOnClickGesellschaftsform}>
Anstatt hier einen Onclick handler zu definieren, macht es eigentlich mehr sinn, den button mit einer <Link> Komponente zu wrappen

2022-02-03 02:39 UTC, luis-rieke commented on apps/frontend/src/pages/Index/Index.tsx
> +	);
done 👍

2022-02-03 02:40 UTC, luis-rieke commented on apps/frontend/src/pages/Index/Index.tsx
> +					<Button variant='secondary' onClick={handleOnClickGesellschaftsform}>
done 👍

2022-02-03 18:38 UTC, SkyGuardian42 approved these changes

2022-02-03 22:46 UTC, Jjutho submitted a review, later dismissed

2022-02-03 23:44 UTC, konstantin-spiess approved these changes

2022-02-03 23:45 UTC, merged